version: '3.9'

services:
  app:
    image: openjdk:21-jdk-slim
    container_name: account-tracker
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs/tracker-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: ["java", "-jar", "app.jar"]
    environment:
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    env_file: ./.env
    image: redis:latest
    container_name: Tracker-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
